Received: from carthage.modulargenetics.com (carthage.modulargenetics.com [192.168.23.51])
	by alexandria.modulargenetics.com (Postfix on SuSE Linux) with ESMTP
	id 578E048B0F; Mon, 17 Sep 2007 09:37:04 -0400 (EDT)
Received: by carthage.modulargenetics.com (Postfix on SuSE Linux, from userid 503)
	id 4927E45BD1; Mon, 17 Sep 2007 09:37:04 -0400 (EDT)
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-ID: <18158.33536.121051.363312@carthage.modulargenetics.com>
X-Mailer: VM 7.19 under Emacs 21.3.1
Organization: Modular Genetics Inc.
From: Bob Rogers <rogers@modulargenetics.com>
To: somebody@modulargenetics.com
Subject: Stuff to do
Date: Mon, 17 Sep 2007 09:37:04 -0400

message message message
