Received: from gateway2.monsanto.com (gateway2.monsanto.com [199.89.234.138])
	by alexandria.modulargenetics.com (Postfix on SuSE Linux) with ESMTP
	id 7545D48A32; Mon, 17 Sep 2007 09:53:50 -0400 (EDT)
Received: from NA1000EXR02.na.ds.monsanto.com (na1000exr02.na.ds.monsanto.com [10.30.64.35])
	by gateway2.monsanto.com (Switch-3.2.7/Switch-3.2.7) with ESMTP id l8HDrHpn016595;
	Mon, 17 Sep 2007 08:53:49 -0500 (CDT)
Received: from NA1000EXR01.na.ds.monsanto.com ([10.30.64.28]) by NA1000EXR02.na.ds.monsanto.com with Microsoft SMTPSVC(6.0.3790.1830); Mon, 17 Sep 2007 08:52:55 -0500
Received: from NA1000EXR03.na.ds.monsanto.com ([10.30.64.44]) by NA1000EXR01.na.ds.monsanto.com with Microsoft SMTPSVC(6.0.3790.1830); Mon, 17 Sep 2007 08:52:55 -0500
Received: from NA2551EXM01.na.ds.monsanto.com ([10.26.12.12]) by NA1000EXR03.na.ds.monsanto.com with Microsoft SMTPSVC(6.0.3790.1830); Mon, 17 Sep 2007 08:52:54 -0500
Content-class: urn:content-classes:message
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----_=_NextPart_001_01C7F932.0B4A8A62"
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.3790.2929
Content-Transfer-Encoding: 7bit
Message-ID: <8F039817F666C24BB296C135151ED7EE01E8288C@NA2551EXM01.na.ds.monsanto.com>
In-Reply-To: <20070917134606.A0D69489A1@alexandria.modulargenetics.com>
X-MS-Has-Attach: 
X-MS-TNEF-Correlator: 
Thread-Topic: All Staff Room on Tuesday, Sept. 18
Thread-Index: Acf3GVn8wfJiUZAGS5WGRbb2iCDCYwCGEESwAAAVsLA=
Importance: normal
Priority: normal
References: <8F039817F666C24BB296C135151ED7EE01E82844@NA2551EXM01.na.ds.monsanto.com> <20070917134606.A0D69489A1@alexandria.modulargenetics.com>
X-OriginalArrivalTime: 17 Sep 2007 13:52:54.0818 (UTC) FILETIME=[0BFD5020:01C7F932]
From: "EMPLOYEE, RANDOM [AG/2076]" <random.j.employee@monsanto.com>
To: Somebody <somebody@modulargenetics.com>,
	"Somebody Else" <selse@modulargenetics.com>
CC: "More People" <more.people@monsanto.com>,
	"All" <all@modulargenetics.com>
Subject: RE: All Staff Room on Tuesday, Sept. 18
Date: Mon, 17 Sep 2007 09:52:52 -0400

message message message
