Received: by alexandria.modulargenetics.com (Postfix on SuSE Linux, from userid 0)
	id 4517E48A61; Wed, 19 Sep 2007 11:28:21 -0400 (EDT)
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-ID: <18161.16405.108775.825363@alexandria.modulargenetics.com>
X-Mailer: VM 7.19 under Emacs 21.2.1
Organization: Modular Genetics Inc.
From: root <@modulargenetics.com>
To: rogers@modulargenetics.com
Subject: test message
Date: Wed, 19 Sep 2007 11:28:21 -0400

   Sent from alexandria.

					-- Bob
