#!/bin/csh -f
#
# Force qmail to re-examine its control files.
#
#    Modification history:
#
# created (from qmail-redeliver).  -- rgr, 19-Feb-00.
#

kill -HUP `ps aux | grep 'qmail[-]send' | cut -c8-14`
