#!/bin/bash
#
#    Do batch tripwire verification.  This is meant to be used as a cron job.
#
#    Modification history:
#
# created.  -- rgr, 12-Jan-02.
# oops; must also verify the tw.config file.  -- rgr, 12-Sep-02.
# updated for SuSE 8.1.  -- rgr, 12-Aug-03.
#

cd /etc
/usr/bin/gpg --verify tw.config.sig tw.config
cd /etc/tw
/usr/bin/gpg --verify tw.db_rgrjr.sig tw.db_rgrjr
# time /usr/sbin/tripwire -q
time /usr/sbin/tripwire
